// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Data;

namespace Web_Data.Migrations
{
    [DbContext(typeof(ImDbContext))]
    [Migration("20220411003147_addata")]
    partial class addata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_Data.BinhLuan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<int>("SanPham_ID")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SanPhamID");

                    b.HasIndex("User_ID");

                    b.ToTable("im_Comment");
                });

            modelBuilder.Entity("Web_Data.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoaDon_ID")
                        .HasColumnType("int");

                    b.Property<int>("KhuyenMai")
                        .HasColumnType("int");

                    b.Property<string>("SoLuong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDon_ID");

                    b.ToTable("im_Invoice_Detail");
                });

            modelBuilder.Entity("Web_Data.DanhMuc", b =>
                {
                    b.Property<string>("ID_DanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDanhMuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_DanhMuc");

                    b.ToTable("im_Category");

                    b.HasData(
                        new
                        {
                            ID_DanhMuc = "DM1",
                            TenDanhMuc = "NEW PRODUCTS",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID_DanhMuc = "DM2",
                            TenDanhMuc = "LATEST PRODUCTS",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID_DanhMuc = "DM3",
                            TenDanhMuc = "BEST SELLERS",
                            TrangThai = "1"
                        });
                });

            modelBuilder.Entity("Web_Data.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("User_ID");

                    b.ToTable("im_Invoice");
                });

            modelBuilder.Entity("Web_Data.LoaiSanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NhaCungCap")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NhaCungCap");

                    b.ToTable("im_Product_Type");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NhaCungCap = 1,
                            TenLoai = "Smartphone Samsung",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 2,
                            NhaCungCap = 2,
                            TenLoai = "iPhone",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 3,
                            NhaCungCap = 3,
                            TenLoai = "Laptop Asus Gaming",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 4,
                            NhaCungCap = 2,
                            TenLoai = "Macbook",
                            TrangThai = "1"
                        });
                });

            modelBuilder.Entity("Web_Data.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("im_Supplier");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DiaChi = "Yên Trung, Yên Phong, Bắc Ninh",
                            TenNCC = "Samsung Electronics Vietnam",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 2,
                            DiaChi = "121 Đ. Lê Lợi, Phường Bến Thành, Quận 1, Thành phố Hồ Chí Minh",
                            TenNCC = "F.Studio (by FPT) - Apple Authorized Reseller",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 3,
                            DiaChi = "264 Nguyễn Thị Minh Khai, Phường 6, Quận 3, Thành phố Hồ Chí Minh",
                            TenNCC = "ASUS ROG Store",
                            TrangThai = "1"
                        });
                });

            modelBuilder.Entity("Web_Data.SanPham", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<int>("GiaMoi")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image_List")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DanhMuc");

                    b.HasIndex("MaLoai");

                    b.ToTable("im_Product");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DanhMuc = "DM1",
                            Gia = 33490000,
                            GiaMoi = 33499000,
                            MaLoai = 3,
                            NgayLap = new DateTime(2022, 4, 11, 7, 31, 47, 264, DateTimeKind.Local).AddTicks(658),
                            Size = "128GB",
                            SoLuong = 7,
                            TenSP = "iPhone 12 Pro Max",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 2,
                            DanhMuc = "DM1",
                            Gia = 33490000,
                            GiaMoi = 33499000,
                            MaLoai = 2,
                            NgayLap = new DateTime(2022, 4, 11, 7, 31, 47, 265, DateTimeKind.Local).AddTicks(970),
                            Size = "128GB",
                            SoLuong = 7,
                            TenSP = "iPhone 12",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 3,
                            DanhMuc = "DM1",
                            Gia = 23990000,
                            GiaMoi = 23490000,
                            Image = "2.png",
                            Image_List = "22nd.png",
                            MaLoai = 2,
                            NgayLap = new DateTime(2022, 4, 11, 7, 31, 47, 265, DateTimeKind.Local).AddTicks(1389),
                            Size = "256GB",
                            SoLuong = 3,
                            TenSP = "iPhone 12 Pro",
                            TrangThai = "1"
                        },
                        new
                        {
                            ID = 4,
                            DanhMuc = "DM1",
                            Gia = 33490000,
                            GiaMoi = 33499000,
                            Image = "4.png",
                            Image_List = "42nd.png",
                            MaLoai = 2,
                            NgayLap = new DateTime(2022, 4, 11, 7, 31, 47, 265, DateTimeKind.Local).AddTicks(1396),
                            Size = "128GB",
                            SoLuong = 7,
                            TenSP = "iPhone 12 Mini",
                            TrangThai = "1"
                        });
                });

            modelBuilder.Entity("Web_Data.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("im_User");
                });

            modelBuilder.Entity("Web_Data.BinhLuan", b =>
                {
                    b.HasOne("Web_Data.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamID");

                    b.HasOne("Web_Data.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Data.ChiTietHoaDon", b =>
                {
                    b.HasOne("Web_Data.HoaDon", "HoaDon")
                        .WithMany("lstCTHD")
                        .HasForeignKey("HoaDon_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("Web_Data.HoaDon", b =>
                {
                    b.HasOne("Web_Data.User", "User")
                        .WithMany("lstHoaDon")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Data.LoaiSanPham", b =>
                {
                    b.HasOne("Web_Data.NhaCungCap", "MaNCC")
                        .WithMany("lstLoaiSanPham")
                        .HasForeignKey("NhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNCC");
                });

            modelBuilder.Entity("Web_Data.SanPham", b =>
                {
                    b.HasOne("Web_Data.DanhMuc", "DMuc")
                        .WithMany("dmucSanPham")
                        .HasForeignKey("DanhMuc");

                    b.HasOne("Web_Data.LoaiSanPham", "Loai")
                        .WithMany("lstSanPham")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DMuc");

                    b.Navigation("Loai");
                });

            modelBuilder.Entity("Web_Data.DanhMuc", b =>
                {
                    b.Navigation("dmucSanPham");
                });

            modelBuilder.Entity("Web_Data.HoaDon", b =>
                {
                    b.Navigation("lstCTHD");
                });

            modelBuilder.Entity("Web_Data.LoaiSanPham", b =>
                {
                    b.Navigation("lstSanPham");
                });

            modelBuilder.Entity("Web_Data.NhaCungCap", b =>
                {
                    b.Navigation("lstLoaiSanPham");
                });

            modelBuilder.Entity("Web_Data.User", b =>
                {
                    b.Navigation("lstHoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
